// AUTH
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

// CREATE
export const UPDATE_EVENT_NAME = 'UPDATE_EVENT_NAME';
export const UPDATE_NAME_TYPE = 'UPDATE_NAME_TYPE';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const RESET_CREATE = 'RESET_CREATE';

// SURVEYS
export const LOAD_SURVEYS_START = 'LOAD_SURVEYS_START';
export const LOAD_SURVEYS_SUCCESS = 'LOAD_SURVEYS_SUCCESS';
export const LOAD_SURVEYS_FAILURE = 'LOAD_SURVEYS_FAILURE';

// SUBMIT
export const SET_SURVEY = 'SET_SURVEY';
export const SET_TIMEFRAMES = 'SET_TIMEFRAMES';

// NOTIFICATION
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';