// AUTH
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

// CREATE
export const UPDATE_EVENT_NAME = 'UPDATE_EVENT_NAME';
export const UPDATE_NAME_TYPE = 'UPDATE_NAME_TYPE';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const RESET_CREATE = 'RESET_CREATE';

// SURVEYS
export const LOAD_SURVEYS_START = 'LOAD_SURVEYS_START';
export const LOAD_SURVEYS_SUCCESS = 'LOAD_SURVEYS_SUCCESS';
export const LOAD_SURVEYS_FAILURE = 'LOAD_SURVEYS_FAILURE';